language: android
# Allows to install dependencies via apt-get when using Travis's new container-based infrastructure.
sudo: false
android:
  components:
    # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-25
    - extra-android-m2repository